### ISSUE TITLE
Windows cannot install required files

### ISSUE THREAD

**Issue by 9helix** [winapps-org/winapps#361]
During the installation of Windows, this is the error that occurs:
![image](https://github.com/user-attachments/assets/035579af-dc71-460c-b0e5-ec3ee36d95a3)

## Steps to reproduce
After cloning the repo in the home directory and starting the installation using 
```
cd winapps
docker compose --file ./compose.yaml up
```
this is the output in the terminal:
```
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
WinApps  | BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
WinApps  | BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
WinApps  | ❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```
When connecting to the VNC the above error shows up shortly after installation starts.

## Neofech
```
                     ./o.                  helix@Ephemeris 
                   ./sssso-                --------------- 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: B550M DS3H -CF 
             `-/ossssssssssssso/.          Kernel: 6.12.4-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 3 hours, 13 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1441 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.37 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: Plasma 6.2.4 
  `:////ssssssssssssssssssssssssssso+++.   WM: kwin 
`-////+ssssssssssssssssssssssssssso++++-   Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Icons: breeze-dark [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Terminal: konsole 
  `:::::::::::::::::::::::::------``       CPU: AMD Ryzen 5 5600 (12) @ 4.468GHz 
                                           GPU: NVIDIA GeForce RTX 3060 Ti GDDR6X 
                                           Memory: 9774MiB / 32017MiB 

                                                                   
```

**Comment by oskardotglobal** [comment]
Did you run the installation before moving the compose.yaml?

**Comment by 9helix** [comment]
Yes. I cloned the repo, entered its directory and ran docker-compose without editing compose.yaml

**Comment by oskardotglobal** [comment]
Can you try with the latest commit I just pushed?

**Comment by 9helix** [comment]
I removed the old winapps folder and cloned again. Still the same error.

**Comment by oskardotglobal** [comment]
I'm pretty sure this is an issue upstream

**Comment by oskardotglobal** [comment]
Did you run a `docker compose down` and deleted the volumes after pulling?

**Comment by 9helix** [comment]
No. What value should I provide after `--rmi`?

**Comment by oskardotglobal** [comment]
Ah sorry, it's not `--rmi`, it's `--volumes`

**Comment by 9helix** [comment]
Sorry, realized I had to set password for the Windows account since Im using newest freerdp version

**Comment by 9helix** [comment]
My bad again, had to install Office in Windows to be able to see them. Thanks again for the help!
