### ISSUE TITLE
freerdp_set_last_error_ex ERRCONNECT_CONNECT_FAILED [0x00020006]

### ISSUE THREAD

**Issue by MacroHard-Winux** [winapps-org/winapps#76]
**Info**
Host: Ubuntu 22.04
guest: Windows 10
Virt-manager version: 4.0.0

when running bin/winapps check:
```
[16:12:57:273] [414333:414334] [ERROR][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_FAILED [0x00020006]
[16:12:57:273] [414333:414334] [ERROR][com.freerdp.core] - failed to connect to 192.168.122.188 
```

_You need to accept the security cert the first time you connect (with 'check')_
security cert did not pop up both on Linux nor Windows VM

_Not enabling RDP in the Windows VM_
RDP is enabled
![Screenshot_20240207_161855](https://github.com/winapps-org/winapps/assets/129944538/71a7eaa5-869e-4fed-b897-232a2a8c2c8b)

_Not being able to connect to the IP of the VM_
Win app found the IP of the VM and it is the correct IP 
"failed to connect to 192.168.122.188"

_Incorrect user credentials in ~/.config/winapps/winapps.conf_
I have checked and I have the correct login and password
![image](https://github.com/winapps-org/winapps/assets/129944538/d915ebf2-7bf2-4609-a85f-349b4613dabc)
RDP_USER="Ascend"
RDP_PASS="31neCr@ftVM"
#RDP_DOMAIN="MYDOMAIN"
#RDP_IP="192.168.123.111"
#RDP_SCALE=100
#RDP_FLAGS=""
#MULTIMON="true"
DEBUG="true"

_Not merging install/RDPApps.reg into the VM_
I did merge the reg into the VM I did it 2 more times to make sure

**Comment by SakiiCode** [comment]
Check the IP address, I had this error `BIO_should_retry returned a system error 32: Broken pipe` after the IP address changed

**Comment by MacroHard-Winux** [comment]
I think it is just a one-off thing. Since I redownloaded the ISO and reinstall the VM and it is now fixed :/
The bug seems unreproducible

**Comment by LDprg** [comment]
I will close the issue. Feel free to reopen if the problem reappears.

**Comment by disclaimedication** [comment]
> I think it is just a one-off thing. Since I redownloaded the ISO and reinstall the VM and it is now fixed :/ The bug seems unreproducible

I still face the same issue.
![image](https://github.com/winapps-org/winapps/assets/33714517/6bf3fd5b-39b6-4e82-83f2-7f4fbdcb00f6)

**Comment by disclaimedication** [comment]
> Generally speaking, it seems like a network issue. Try to test your connection tp the vm (with for example a ping).

Apologies, yes, it was a network issue. It is fixed now. Thanks for the prompt response.

**Comment by vetens** [comment]
I seem to be having the same issue, with a linux client and windows 10 server:
![freerdp_issue_redacted](https://github.com/user-attachments/assets/3276a6a4-5207-4f5b-a6d0-882e2041a6cf)
my client firewall has already been disabled, and as you can see from the ping, it is not a network issue either.

**Comment by DaRandomCube** [comment]
the problem reappeared with me, how do i fix it without reinstalling the vm? and how do i check the connection with vm using ping?
